server:
  host: '10.9.44.5'
  http_port: 8081
mysql:
  name: 'ai_center'
  user: 'root'
  password: '123456'
  host: '127.0.0.1'
  port: 3306
  max_connections: 900
mcp:
  host: '127.0.0.1'
  port: 8082
  enabled: false
