server:
  host: '10.9.44.5'
  http_port: 8081
mysql:
  name: 'ai_center'
  user: 'root'
  password: '123456'
  host: '10.9.44.5'
  port: 3306
  max_connections: 900
mcp:
  host: '10.9.44.5'
  port: 8082
  enabled: true
es:
  host: '10.9.44.5'
  port: 9200
  username: 'elastic'
  password: '123456'
  scheme: 'https'
redis:
  db: 1
  username: ''
  password: ''
  host: '10.9.44.5'
  port: 6379
rustfs:
  username: 'rustfsadmin'
  password: 'rustfsadmin'
  host: '10.9.44.5'
  port: 9000
logging:
  level: 'INFO'
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'